# Generated by Django 4.2.3 on 2023-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
